language: c
sudo: false

env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
    - secure: "dkhvrkbNEHv55q3NU+lNJ0SqaNG0/vPMsG3X2eQvYjFsq/e8EliILtEtjrugSgeFohxqms0F+sSyDpw46mtn+jukYejdywLVL7w8o9pxlkHv8uEqYhNiwCD8RjNyRPQAS9jL+sAJiqdqUWR6AzjwaLproCe6rFzzGe7Io5oDLMg="
    - secure: "cfosGf5hvUhIlPoGJu0d/HFddrMwIFU7FfLwd8yRrMGkYv0ePOwAW9kmhFSxUYvuXkxzgD75cIICMFY2fSm6VXBXXzfPQD7vwzoApXf7a8vi0C64XhinXhdEyUYb5/v8fswa0zheUENYhUS1tOqDXT/h8EPNZT5wKizaA3O2Wa8="
    - secure: "QXuqKYuwCocqsTMePBc5OugBbQC4/t+335TYLdkletiateP/rF/eDsVRG792/BVq5gKRZgz3NH9ipTNm5pZoCbAEPt9+eDpfts8WeAbxmjdcEjfBxxwZ69wUTPAVrezTGn2k7W2UBdFrWeUNKPAVCKIkoviXqOHFitqJEC+c6JY="
    - secure: "jIyBEzR10l5SWvY5ouEYzA8YzPHIZNMXMBdcXwuwte8NCU8GBYUqhHA1L67nTaBdLhWbrZ2NireVKPQWJp3ctcI0IB6xZzaYlVpgN/udGPO+1MZd9Xhp9TWuJWrGZ9EoWGB9L5H+O7RYwcDMVH5CUrCIBdsSJuyE8aDpky1/IVE="

stages:
  - test

before_install:
  - cd ..
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  # Update conda
  - conda update --yes conda
  - conda info -a

jobs:
  include:
    - stage: test
      install:
        - conda create -y -c rmg -n rmg_env rmg
        - source activate rmg_env
        - which rmg.py
      script:
        - rmg.py RMG-Py/examples/rmg/minimal/input.py
        - rmg.py RMG-Py/examples/rmg/1,3-hexadiene/input.py
        - rmg.py RMG-Py/examples/rmg/liquid_phase/input.py
        - thermoEstimator.py RMG-Py/examples/thermoEstimator/input.py
        - rmg.py RMG-Py/examples/rmg/heptane-eg5/input.py
        - rmg.py RMG-Py/examples/rmg/ethane-oxidation/input.py
        - rmg.py RMG-Py/examples/rmg/gri_mech_rxn_lib/input.py
    - os: osx
      install:
        - conda create -y -c rmg -n rmg_env rmg
        - source activate rmg_env
        - which rmg.py
      script:
        - rmg.py RMG-Py/examples/rmg/minimal/input.py
        - rmg.py RMG-Py/examples/rmg/1,3-hexadiene/input.py
        - rmg.py RMG-Py/examples/rmg/liquid_phase/input.py
        - thermoEstimator.py RMG-Py/examples/thermoEstimator/input.py
        - rmg.py RMG-Py/examples/rmg/heptane-eg5/input.py
        - rmg.py RMG-Py/examples/rmg/ethane-oxidation/input.py
        - rmg.py RMG-Py/examples/rmg/gri_mech_rxn_lib/input.py
