name: rmg_gnn_env
channels:
  - conda-forge
  - krsna
  - pytorch
  - dglteam
dependencies:
  - cairo #conda forge
  - cairocffi #conda forge no arch
  - cantera >=2.4.0 #conda forge
  - cclib #conda forge
  - coolprop #conda forge
  - coverage #conda forge
  - cython >=0.25.2 #conda forge
  - ffmpeg #conda forge
  - gprof2dot #conda forge
  - graphviz #conda forge
  - h5py #conda forge
  - jinja2 #conda forge
  - jupyter #conda forge
  - lpsolve55 #conda forge
  - markupsafe #conda forge
  - matplotlib >=1.5 #conda forge
  - mpmath #conda forge
  - muq #needs rebuilding maybe
  - networkx #conda forge
  - nose #conda forge
  - numdifftools #conda forge
  - numpy #conda forge
  - openbabel #conda forge
  - pandas #conda forge
  - psutil #conda forge
  - pydot #conda forge
  - pymongo #conda forge
  - pyparsing #conda forge
  - python =3.8
  - pip
  - pyyaml #conda forge
  - quantities #conda forge
  - rdkit=2020.03.4 #conda forge
  - scikit-learn #conda forge
  - scipy #conda forge
  - xlrd #no arch
  - xlwt #no arch
  #ml
  # inbuilt SiLU
  - pytorch=1.7
  - pytorch-lightning=1.1
  - cpuonly
  #better kernels
  - dgl=0.6
  - sympy
  # utilities
  - typer
  - pydantic
  - tqdm
  # for gnns thermo tests
  - pytest
  # just in case
  - make
  - cmake
  - pip:
      - dgllife==0.2.6
