name: rmg_gnn_env
channels:
  - defaults
  - rmg
  - conda-forge
dependencies:
  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - conda-forge::cclib >=1.6.3
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=1.5
  - rmg::mopac
  - mpmath
  - rmg::muq2
  - networkx
  - nose
  - rmg::numdifftools
  - numpy >=1.10.0
  - conda-forge::openbabel >= 3
  - pandas
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - rmg::symmetry
  - xlrd
  - xlwt
  #dimenetpp featurization 
  - ase # to run geometry optimization
  - xtb-python #to get forces and energies from xTB
  #ml
  #oldest version of torch compatible with dgl 
  #and doesn't result in segfaults or numpy errors
  - pytorch::pytorch=1.5
  - pytorch::cpuonly
  #better kernels
  - dglteam::dgl=0.6
  #for dimenetpp
  - sympy
  # utilities
  - typer
  - pydantic
  - tqdm
  # for gnns thermo tests
  - pytest
  # just in case
  - make
  - cmake
  - gcc_linux-64=7.3
  - pip:
    #lots of cheminformatics utilities 
      - dgllife==0.2.6
